AppName = "project-name"
Port = ":8080"
Stage = "test"

URL = "http://localhost:8080/"

EmailNotifyList = [
    "david.chou93@gmail.com",
]

[BasicAuth]
Account = "metro"
Password = "Aa111111"

[Limiter]
Limit = 1
Burst = 500

[PostgresConf]
Host = "localhost"
Port = "5432"
User = "david"
DBName = "localtest"
Password = "Start123"